title: 'b2a3e8.github.io'
description: "A blog of books."
baseurl: "/blog-books"
url: "https://b2a3e8.github.io"

header_pages:
  - index.md
  - about.md
  - contact.md

style: dark

footer: '...'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
